openapi: 3.1.0
info:
  title: auser API
  description: This is the auser API.
  contact:
    email: mority@posteo.net
  license:
    name: MIT
    url: https://opensource.org/license/mit
  version: v1
externalDocs:
  description: Find out more about MOTIS
  url: https://github.com/motis-project/motis
paths:
  /api/v1/get_updates:
    get:
      summary: compiles all VDV AUS updates that arrived after the specified update ID into a single AUSNachricht
      operationId: get_updates
      parameters:
        - name: since
          in: query
          required: true
          description:
            ID of the previous update of the data consumer, zero in case of initial update
          schema:
            type: integer
            default: 0

      responses:
        '200':
          description: new update ID and a VDV AUSNachricht containing all updates that arrived after the one with the given ID
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    description: "the ID of this update"
                    type: integer
                  update:
                    description: "VDV AUSNachricht xml"
                    type: string